name: connectivity
description: This is a updated version of flutter official connectivity plugin.
homepage: https://github.com/flutter/plugins/tree/master/packages/connectivity/connectivity
version: 0.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.connectivity
        pluginClass: ConnectivityPlugin
      ios:
        pluginClass: FLTConnectivityPlugin
      macos:
        default_package: connectivity_macos

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.0.5"
  plugin_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.2.0
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.0
  pedantic: ^1.8.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
